/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    ConfirmDeleteDialog: typeof import('./src/components/dialogs/ConfirmDeleteDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
