/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/AccountingDocumentCreate': RouteRecordInfo<'/AccountingDocumentCreate', '/AccountingDocumentCreate', Record<never, never>, Record<never, never>>,
    '/AccountingDocumentList': RouteRecordInfo<'/AccountingDocumentList', '/AccountingDocumentList', Record<never, never>, Record<never, never>>,
    '/BalanceSheet': RouteRecordInfo<'/BalanceSheet', '/BalanceSheet', Record<never, never>, Record<never, never>>,
    '/BankCashDefinition': RouteRecordInfo<'/BankCashDefinition', '/BankCashDefinition', Record<never, never>, Record<never, never>>,
    '/CashFlow': RouteRecordInfo<'/CashFlow', '/CashFlow', Record<never, never>, Record<never, never>>,
    '/CashPayment': RouteRecordInfo<'/CashPayment', '/CashPayment', Record<never, never>, Record<never, never>>,
    '/CashReceipt': RouteRecordInfo<'/CashReceipt', '/CashReceipt', Record<never, never>, Record<never, never>>,
    '/ChartOfAccounts': RouteRecordInfo<'/ChartOfAccounts', '/ChartOfAccounts', Record<never, never>, Record<never, never>>,
    '/ChequeManagement': RouteRecordInfo<'/ChequeManagement', '/ChequeManagement', Record<never, never>, Record<never, never>>,
    '/CreatePersonnel': RouteRecordInfo<'/CreatePersonnel', '/CreatePersonnel', Record<never, never>, Record<never, never>>,
    '/CustomersDefinition': RouteRecordInfo<'/CustomersDefinition', '/CustomersDefinition', Record<never, never>, Record<never, never>>,
    '/FiscalYear': RouteRecordInfo<'/FiscalYear', '/FiscalYear', Record<never, never>, Record<never, never>>,
    '/HomePage': RouteRecordInfo<'/HomePage', '/HomePage', Record<never, never>, Record<never, never>>,
    '/IncomeStatement': RouteRecordInfo<'/IncomeStatement', '/IncomeStatement', Record<never, never>, Record<never, never>>,
    '/ItemKardex': RouteRecordInfo<'/ItemKardex', '/ItemKardex', Record<never, never>, Record<never, never>>,
    '/LoginPage': RouteRecordInfo<'/LoginPage', '/LoginPage', Record<never, never>, Record<never, never>>,
    '/MonthlyAttendance': RouteRecordInfo<'/MonthlyAttendance', '/MonthlyAttendance', Record<never, never>, Record<never, never>>,
    '/PayrollCalculation': RouteRecordInfo<'/PayrollCalculation', '/PayrollCalculation', Record<never, never>, Record<never, never>>,
    '/PaySlip': RouteRecordInfo<'/PaySlip', '/PaySlip', Record<never, never>, Record<never, never>>,
    '/PersonnelContracts': RouteRecordInfo<'/PersonnelContracts', '/PersonnelContracts', Record<never, never>, Record<never, never>>,
    '/PersonnelList': RouteRecordInfo<'/PersonnelList', '/PersonnelList', Record<never, never>, Record<never, never>>,
    '/ProductDefinition': RouteRecordInfo<'/ProductDefinition', '/ProductDefinition', Record<never, never>, Record<never, never>>,
    '/ProformaInvoice': RouteRecordInfo<'/ProformaInvoice', '/ProformaInvoice', Record<never, never>, Record<never, never>>,
    '/PurchaseInvoice': RouteRecordInfo<'/PurchaseInvoice', '/PurchaseInvoice', Record<never, never>, Record<never, never>>,
    '/PurchaseOrder': RouteRecordInfo<'/PurchaseOrder', '/PurchaseOrder', Record<never, never>, Record<never, never>>,
    '/PurchaseReturn': RouteRecordInfo<'/PurchaseReturn', '/PurchaseReturn', Record<never, never>, Record<never, never>>,
    '/RegisterPage': RouteRecordInfo<'/RegisterPage', '/RegisterPage', Record<never, never>, Record<never, never>>,
    '/SalesInvoice': RouteRecordInfo<'/SalesInvoice', '/SalesInvoice', Record<never, never>, Record<never, never>>,
    '/SalesReports': RouteRecordInfo<'/SalesReports', '/SalesReports', Record<never, never>, Record<never, never>>,
    '/SalesReturn': RouteRecordInfo<'/SalesReturn', '/SalesReturn', Record<never, never>, Record<never, never>>,
    '/SuppliersDefinition': RouteRecordInfo<'/SuppliersDefinition', '/SuppliersDefinition', Record<never, never>, Record<never, never>>,
    '/TaxpayersReport': RouteRecordInfo<'/TaxpayersReport', '/TaxpayersReport', Record<never, never>, Record<never, never>>,
    '/UserManagment': RouteRecordInfo<'/UserManagment', '/UserManagment', Record<never, never>, Record<never, never>>,
    '/WarehouseDefinition': RouteRecordInfo<'/WarehouseDefinition', '/WarehouseDefinition', Record<never, never>, Record<never, never>>,
    '/WarehouseInventory': RouteRecordInfo<'/WarehouseInventory', '/WarehouseInventory', Record<never, never>, Record<never, never>>,
    '/WarehouseIssue': RouteRecordInfo<'/WarehouseIssue', '/WarehouseIssue', Record<never, never>, Record<never, never>>,
    '/WarehouseReceipt': RouteRecordInfo<'/WarehouseReceipt', '/WarehouseReceipt', Record<never, never>, Record<never, never>>,
    '/WarehouseTransfer': RouteRecordInfo<'/WarehouseTransfer', '/WarehouseTransfer', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/AccountingDocumentCreate.vue': {
      routes: '/AccountingDocumentCreate'
      views: never
    }
    'src/pages/AccountingDocumentList.vue': {
      routes: '/AccountingDocumentList'
      views: never
    }
    'src/pages/BalanceSheet.vue': {
      routes: '/BalanceSheet'
      views: never
    }
    'src/pages/BankCashDefinition.vue': {
      routes: '/BankCashDefinition'
      views: never
    }
    'src/pages/CashFlow.vue': {
      routes: '/CashFlow'
      views: never
    }
    'src/pages/CashPayment.vue': {
      routes: '/CashPayment'
      views: never
    }
    'src/pages/CashReceipt.vue': {
      routes: '/CashReceipt'
      views: never
    }
    'src/pages/ChartOfAccounts.vue': {
      routes: '/ChartOfAccounts'
      views: never
    }
    'src/pages/ChequeManagement.vue': {
      routes: '/ChequeManagement'
      views: never
    }
    'src/pages/CreatePersonnel.vue': {
      routes: '/CreatePersonnel'
      views: never
    }
    'src/pages/CustomersDefinition.vue': {
      routes: '/CustomersDefinition'
      views: never
    }
    'src/pages/FiscalYear.vue': {
      routes: '/FiscalYear'
      views: never
    }
    'src/pages/HomePage.vue': {
      routes: '/HomePage'
      views: never
    }
    'src/pages/IncomeStatement.vue': {
      routes: '/IncomeStatement'
      views: never
    }
    'src/pages/ItemKardex.vue': {
      routes: '/ItemKardex'
      views: never
    }
    'src/pages/LoginPage.vue': {
      routes: '/LoginPage'
      views: never
    }
    'src/pages/MonthlyAttendance.vue': {
      routes: '/MonthlyAttendance'
      views: never
    }
    'src/pages/PayrollCalculation.vue': {
      routes: '/PayrollCalculation'
      views: never
    }
    'src/pages/PaySlip.vue': {
      routes: '/PaySlip'
      views: never
    }
    'src/pages/PersonnelContracts.vue': {
      routes: '/PersonnelContracts'
      views: never
    }
    'src/pages/PersonnelList.vue': {
      routes: '/PersonnelList'
      views: never
    }
    'src/pages/ProductDefinition.vue': {
      routes: '/ProductDefinition'
      views: never
    }
    'src/pages/ProformaInvoice.vue': {
      routes: '/ProformaInvoice'
      views: never
    }
    'src/pages/PurchaseInvoice.vue': {
      routes: '/PurchaseInvoice'
      views: never
    }
    'src/pages/PurchaseOrder.vue': {
      routes: '/PurchaseOrder'
      views: never
    }
    'src/pages/PurchaseReturn.vue': {
      routes: '/PurchaseReturn'
      views: never
    }
    'src/pages/RegisterPage.vue': {
      routes: '/RegisterPage'
      views: never
    }
    'src/pages/SalesInvoice.vue': {
      routes: '/SalesInvoice'
      views: never
    }
    'src/pages/SalesReports.vue': {
      routes: '/SalesReports'
      views: never
    }
    'src/pages/SalesReturn.vue': {
      routes: '/SalesReturn'
      views: never
    }
    'src/pages/SuppliersDefinition.vue': {
      routes: '/SuppliersDefinition'
      views: never
    }
    'src/pages/TaxpayersReport.vue': {
      routes: '/TaxpayersReport'
      views: never
    }
    'src/pages/UserManagment.vue': {
      routes: '/UserManagment'
      views: never
    }
    'src/pages/WarehouseDefinition.vue': {
      routes: '/WarehouseDefinition'
      views: never
    }
    'src/pages/WarehouseInventory.vue': {
      routes: '/WarehouseInventory'
      views: never
    }
    'src/pages/WarehouseIssue.vue': {
      routes: '/WarehouseIssue'
      views: never
    }
    'src/pages/WarehouseReceipt.vue': {
      routes: '/WarehouseReceipt'
      views: never
    }
    'src/pages/WarehouseTransfer.vue': {
      routes: '/WarehouseTransfer'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
