/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/accounting/AccountingDocumentCreate': RouteRecordInfo<'/accounting/AccountingDocumentCreate', '/accounting/AccountingDocumentCreate', Record<never, never>, Record<never, never>>,
    '/accounting/AccountingDocumentList': RouteRecordInfo<'/accounting/AccountingDocumentList', '/accounting/AccountingDocumentList', Record<never, never>, Record<never, never>>,
    '/accounting/ChartOfAccounts': RouteRecordInfo<'/accounting/ChartOfAccounts', '/accounting/ChartOfAccounts', Record<never, never>, Record<never, never>>,
    '/accounting/FiscalYear': RouteRecordInfo<'/accounting/FiscalYear', '/accounting/FiscalYear', Record<never, never>, Record<never, never>>,
    '/auth/LoginPage': RouteRecordInfo<'/auth/LoginPage', '/auth/LoginPage', Record<never, never>, Record<never, never>>,
    '/auth/RegisterPage': RouteRecordInfo<'/auth/RegisterPage', '/auth/RegisterPage', Record<never, never>, Record<never, never>>,
    '/home/HomePage': RouteRecordInfo<'/home/HomePage', '/home/HomePage', Record<never, never>, Record<never, never>>,
    '/hr/CreatePersonnel': RouteRecordInfo<'/hr/CreatePersonnel', '/hr/CreatePersonnel', Record<never, never>, Record<never, never>>,
    '/hr/MonthlyAttendance': RouteRecordInfo<'/hr/MonthlyAttendance', '/hr/MonthlyAttendance', Record<never, never>, Record<never, never>>,
    '/hr/PayrollCalculation': RouteRecordInfo<'/hr/PayrollCalculation', '/hr/PayrollCalculation', Record<never, never>, Record<never, never>>,
    '/hr/PaySlip': RouteRecordInfo<'/hr/PaySlip', '/hr/PaySlip', Record<never, never>, Record<never, never>>,
    '/hr/PersonnelContracts': RouteRecordInfo<'/hr/PersonnelContracts', '/hr/PersonnelContracts', Record<never, never>, Record<never, never>>,
    '/hr/PersonnelList': RouteRecordInfo<'/hr/PersonnelList', '/hr/PersonnelList', Record<never, never>, Record<never, never>>,
    '/inventory/ItemKardex': RouteRecordInfo<'/inventory/ItemKardex', '/inventory/ItemKardex', Record<never, never>, Record<never, never>>,
    '/inventory/ProductDefinition': RouteRecordInfo<'/inventory/ProductDefinition', '/inventory/ProductDefinition', Record<never, never>, Record<never, never>>,
    '/inventory/WarehouseDefinition': RouteRecordInfo<'/inventory/WarehouseDefinition', '/inventory/WarehouseDefinition', Record<never, never>, Record<never, never>>,
    '/inventory/WarehouseInventory': RouteRecordInfo<'/inventory/WarehouseInventory', '/inventory/WarehouseInventory', Record<never, never>, Record<never, never>>,
    '/inventory/WarehouseIssue': RouteRecordInfo<'/inventory/WarehouseIssue', '/inventory/WarehouseIssue', Record<never, never>, Record<never, never>>,
    '/inventory/WarehouseReceipt': RouteRecordInfo<'/inventory/WarehouseReceipt', '/inventory/WarehouseReceipt', Record<never, never>, Record<never, never>>,
    '/inventory/WarehouseTransfer': RouteRecordInfo<'/inventory/WarehouseTransfer', '/inventory/WarehouseTransfer', Record<never, never>, Record<never, never>>,
    '/purchasing/PurchaseInvoice': RouteRecordInfo<'/purchasing/PurchaseInvoice', '/purchasing/PurchaseInvoice', Record<never, never>, Record<never, never>>,
    '/purchasing/PurchaseOrder': RouteRecordInfo<'/purchasing/PurchaseOrder', '/purchasing/PurchaseOrder', Record<never, never>, Record<never, never>>,
    '/purchasing/PurchaseReturn': RouteRecordInfo<'/purchasing/PurchaseReturn', '/purchasing/PurchaseReturn', Record<never, never>, Record<never, never>>,
    '/purchasing/SuppliersDefinition': RouteRecordInfo<'/purchasing/SuppliersDefinition', '/purchasing/SuppliersDefinition', Record<never, never>, Record<never, never>>,
    '/reports/BalanceSheet': RouteRecordInfo<'/reports/BalanceSheet', '/reports/BalanceSheet', Record<never, never>, Record<never, never>>,
    '/reports/IncomeStatement': RouteRecordInfo<'/reports/IncomeStatement', '/reports/IncomeStatement', Record<never, never>, Record<never, never>>,
    '/reports/TaxpayersReport': RouteRecordInfo<'/reports/TaxpayersReport', '/reports/TaxpayersReport', Record<never, never>, Record<never, never>>,
    '/sales/CustomersDefinition': RouteRecordInfo<'/sales/CustomersDefinition', '/sales/CustomersDefinition', Record<never, never>, Record<never, never>>,
    '/sales/ProformaInvoice': RouteRecordInfo<'/sales/ProformaInvoice', '/sales/ProformaInvoice', Record<never, never>, Record<never, never>>,
    '/sales/SalesInvoice': RouteRecordInfo<'/sales/SalesInvoice', '/sales/SalesInvoice', Record<never, never>, Record<never, never>>,
    '/sales/SalesReports': RouteRecordInfo<'/sales/SalesReports', '/sales/SalesReports', Record<never, never>, Record<never, never>>,
    '/sales/SalesReturn': RouteRecordInfo<'/sales/SalesReturn', '/sales/SalesReturn', Record<never, never>, Record<never, never>>,
    '/settings/UserManagment': RouteRecordInfo<'/settings/UserManagment', '/settings/UserManagment', Record<never, never>, Record<never, never>>,
    '/treasury/BankCashDefinition': RouteRecordInfo<'/treasury/BankCashDefinition', '/treasury/BankCashDefinition', Record<never, never>, Record<never, never>>,
    '/treasury/CashFlow': RouteRecordInfo<'/treasury/CashFlow', '/treasury/CashFlow', Record<never, never>, Record<never, never>>,
    '/treasury/CashPayment': RouteRecordInfo<'/treasury/CashPayment', '/treasury/CashPayment', Record<never, never>, Record<never, never>>,
    '/treasury/CashReceipt': RouteRecordInfo<'/treasury/CashReceipt', '/treasury/CashReceipt', Record<never, never>, Record<never, never>>,
    '/treasury/ChequeManagement': RouteRecordInfo<'/treasury/ChequeManagement', '/treasury/ChequeManagement', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/accounting/AccountingDocumentCreate.vue': {
      routes: '/accounting/AccountingDocumentCreate'
      views: never
    }
    'src/pages/accounting/AccountingDocumentList.vue': {
      routes: '/accounting/AccountingDocumentList'
      views: never
    }
    'src/pages/accounting/ChartOfAccounts.vue': {
      routes: '/accounting/ChartOfAccounts'
      views: never
    }
    'src/pages/accounting/FiscalYear.vue': {
      routes: '/accounting/FiscalYear'
      views: never
    }
    'src/pages/auth/LoginPage.vue': {
      routes: '/auth/LoginPage'
      views: never
    }
    'src/pages/auth/RegisterPage.vue': {
      routes: '/auth/RegisterPage'
      views: never
    }
    'src/pages/home/HomePage.vue': {
      routes: '/home/HomePage'
      views: never
    }
    'src/pages/hr/CreatePersonnel.vue': {
      routes: '/hr/CreatePersonnel'
      views: never
    }
    'src/pages/hr/MonthlyAttendance.vue': {
      routes: '/hr/MonthlyAttendance'
      views: never
    }
    'src/pages/hr/PayrollCalculation.vue': {
      routes: '/hr/PayrollCalculation'
      views: never
    }
    'src/pages/hr/PaySlip.vue': {
      routes: '/hr/PaySlip'
      views: never
    }
    'src/pages/hr/PersonnelContracts.vue': {
      routes: '/hr/PersonnelContracts'
      views: never
    }
    'src/pages/hr/PersonnelList.vue': {
      routes: '/hr/PersonnelList'
      views: never
    }
    'src/pages/inventory/ItemKardex.vue': {
      routes: '/inventory/ItemKardex'
      views: never
    }
    'src/pages/inventory/ProductDefinition.vue': {
      routes: '/inventory/ProductDefinition'
      views: never
    }
    'src/pages/inventory/WarehouseDefinition.vue': {
      routes: '/inventory/WarehouseDefinition'
      views: never
    }
    'src/pages/inventory/WarehouseInventory.vue': {
      routes: '/inventory/WarehouseInventory'
      views: never
    }
    'src/pages/inventory/WarehouseIssue.vue': {
      routes: '/inventory/WarehouseIssue'
      views: never
    }
    'src/pages/inventory/WarehouseReceipt.vue': {
      routes: '/inventory/WarehouseReceipt'
      views: never
    }
    'src/pages/inventory/WarehouseTransfer.vue': {
      routes: '/inventory/WarehouseTransfer'
      views: never
    }
    'src/pages/purchasing/PurchaseInvoice.vue': {
      routes: '/purchasing/PurchaseInvoice'
      views: never
    }
    'src/pages/purchasing/PurchaseOrder.vue': {
      routes: '/purchasing/PurchaseOrder'
      views: never
    }
    'src/pages/purchasing/PurchaseReturn.vue': {
      routes: '/purchasing/PurchaseReturn'
      views: never
    }
    'src/pages/purchasing/SuppliersDefinition.vue': {
      routes: '/purchasing/SuppliersDefinition'
      views: never
    }
    'src/pages/reports/BalanceSheet.vue': {
      routes: '/reports/BalanceSheet'
      views: never
    }
    'src/pages/reports/IncomeStatement.vue': {
      routes: '/reports/IncomeStatement'
      views: never
    }
    'src/pages/reports/TaxpayersReport.vue': {
      routes: '/reports/TaxpayersReport'
      views: never
    }
    'src/pages/sales/CustomersDefinition.vue': {
      routes: '/sales/CustomersDefinition'
      views: never
    }
    'src/pages/sales/ProformaInvoice.vue': {
      routes: '/sales/ProformaInvoice'
      views: never
    }
    'src/pages/sales/SalesInvoice.vue': {
      routes: '/sales/SalesInvoice'
      views: never
    }
    'src/pages/sales/SalesReports.vue': {
      routes: '/sales/SalesReports'
      views: never
    }
    'src/pages/sales/SalesReturn.vue': {
      routes: '/sales/SalesReturn'
      views: never
    }
    'src/pages/settings/UserManagment.vue': {
      routes: '/settings/UserManagment'
      views: never
    }
    'src/pages/treasury/BankCashDefinition.vue': {
      routes: '/treasury/BankCashDefinition'
      views: never
    }
    'src/pages/treasury/CashFlow.vue': {
      routes: '/treasury/CashFlow'
      views: never
    }
    'src/pages/treasury/CashPayment.vue': {
      routes: '/treasury/CashPayment'
      views: never
    }
    'src/pages/treasury/CashReceipt.vue': {
      routes: '/treasury/CashReceipt'
      views: never
    }
    'src/pages/treasury/ChequeManagement.vue': {
      routes: '/treasury/ChequeManagement'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
